### ISSUE TITLE
permission to reupload to thunderstore?

### ISSUE THREAD

**Issue by travisclare** [Ivaylo-Lafchiev/ValheimRecycle#10]

**Comment by Ivaylo-Lafchiev** [comment]
Sure.

**Comment by TNoStone** [comment]
> Sure, go for it, but please provide credit.

Of course! :)

**Comment by TNoStone** [comment]
> Sure, go for it, but please provide credit.

Do you think you could update the nexus mods page permissions for the mod to say something like either of:

 
Upload permission
You can upload this file to other sites but you must credit me as the creator of the file
or
 
Upload permission
You must get permission from me before you are allowed to upload my files to other sites

?

**Comment by TNoStone** [comment]
https://valheim.thunderstore.io/package/nexusreupload/Ivaylo_Lafchiev_Deathwalkx_ValheimRecycle/ reupload link

**Comment by Ivaylo-Lafchiev** [comment]
Updated the permissions section on Nexusmods
