### ISSUE TITLE
Seems to be broken (again) with epic loot

### ISSUE THREAD

**Issue by ankemp** [Ivaylo-Lafchiev/ValheimRecycle#5]
Do you mind taking a look?

**Comment by ankemp** [comment]
I'm not sure if this is the issue, as I'm not super familiar with valheim mod code, or it's libraries.
But to me it seems like It's just not reading the value from the config for location.
https://github.com/Ivaylo-Lafchiev/ValheimRecycle/blob/7940c118a1bbd4e2f1aef1eaac1f95094d1d27c8/ValheimRecycle.cs#L39

I'm not sure if this is wrong, or if it will fix the issue.

**Comment by Ivaylo-Lafchiev** [comment]
Can you be more specific about the issue you are facing exactly? Here I am using the latest version of both addons and the recycle tab is displaying/working correctly.

![2021-07-17](https://user-images.githubusercontent.com/10599277/126038079-c6f3accf-5ac1-4671-8386-69b9b05e8e45.png)

**Comment by ankemp** [comment]
This is what I'm seeing, (with the same versions.
![image](https://user-images.githubusercontent.com/3876981/126040891-595b608d-c09e-4bc3-9f56-f4786e153142.png)

Make sure you add the enchanter to the upgrades of the forge.

A -sort of- work around we've found, is if you equip and unequip an item it shows the list of enchantable/dis-enchantable items correctly. But then promptly breaks after you enchant/dis-enchant one item.

**Comment by Ivaylo-Lafchiev** [comment]
Sorry, I still don't understand what the actual problem is. Enchanting and Recycling still seems to work fine for me with the Enchanter using the Forge.

You might want to try disabling any other mods to confirm if the issue isn't coming from somewhere else.

**Comment by ankemp** [comment]
I'll look into other addons, but when I remove recycle it fixes epic loot. I supposed it could be a problem with epic loot.
